# JVM arguments
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Enable Gradle build cache
org.gradle.caching=true

# Enable Configuration Cache
org.gradle.configuration-cache=true

# Run builds in parallel
org.gradle.parallel=true
org.gradle.configureondemand=true

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Reduce R class size
android.nonTransitiveRClass=true

# Use Android Studio bundled JDK

